spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true
      search-paths: config
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/